export const globalStyles: any = {
    colors: {
        white: '#FEFEFE',
        black: '#050505',
        gray: '#BFBFBF',
        primary: '#2E7A3E',
        primaryLight: '#55BA6B',
        primaryShade: '#194E25',
    },
    spacing: {
        min: 2,
        xSmall: 4,
        small: 8,
        medium: 16,
        large: 24,
        xLarge: 36,
        max: 48,
    },
    fontSizes: {
        min: 10,
        xSmall: 12,
        small: 14,
        medium: 18,
        large: 20,
        xLarge: 36,
        max: 48,
    },
    weights: {
        regular: "400",
        medium: "500",
        bold: "700",
        black: "900",
    },
    borderRadius: 8,
}